# For full config options, check the docs:
#    docs.serverless.com


service: txn
frameworkVersion: ">=1.1.0 <2.0.0"
app: rest-api-txn
org: ryanauger

package:
  exclude:
    - lib/node_modules/**

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    AWS_MYSQL_HOST: ${env:AWS_MYSQL_HOST}
    AWS_MYSQL_USERNAME: ${env:AWS_MYSQL_USERNAME}
    AWS_MYSQL_DBNAME: ${env:AWS_MYSQL_DBNAME}
    AWS_MYSQL_PASSWORD: ${env:AWS_MYSQL_PASSWORD}

functions:
  txn-create:
    handler: controllers/create.create
    events:
      - http:
          path: txn
          method: post
          cors: true
          authorizer: txn-authorizer
 txn-fee:
    handler: controllers/fee.checkFee
    events:
      - http:
          path: txn/fee
          method: post
          cors: true
          authorizer: txn-authorizer
  txn-fetch:
    handler: controllers/retreive.retreive
    events:
      - http:
          path: txn/{txn_id}
          method: get
          cors: true
          authorizer: txn-authorizer
  txn-fetch_all:
    handler: controllers/retreive.allForUser
    events:
      - http:
          path: txn
          method: get
          cors: true
          authorizer: txn-authorizer
  txn-update:
    handler: controllers/update.update
    events:
      - http:
          path: txn/{txn_id}
          method: put
          cors: true
          authorizer: txn-authorizer

  txn-authorizer:
    name: txn-authorizer
    handler: lib/controllers/authorizer.defaultAuthorizer
          # authorizer:
          #   name: esgro-users-authorizer
          #   arn: arn:aws:cognito-idp:us-east-1:532299806817:userpool/us-east-1_289MZHUoN
