# For full config options, check the docs:
#    docs.serverless.com

service: user
frameworkVersion: ">=1.1.0 <2.0.0"
app: rest-api-user
org: ryanauger

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    AWS_MYSQL_HOST: ${env:AWS_MYSQL_HOST}
    AWS_MYSQL_USERNAME: ${env:AWS_MYSQL_USERNAME}
    AWS_MYSQL_DBNAME: ${env:AWS_MYSQL_DBNAME}
    AWS_MYSQL_PASSWORD: ${env:AWS_MYSQL_PASSWORD}
    AWS_KEY: ${env:AWS_KEY}
    AWS_SECRET: ${env:AWS_SECRET}
    AWS_DEPLOY_REGION: ${env:AWS_DEPLOY_REGION}
    AWS_USER_REGISTERED_TOPIC_ARN: ${env:AWS_USER_REGISTERED_TOPIC_ARN}
    # AWS_USER_WALLET_REGISTERED_TOPIC_ARN:

functions:
  user-create:
    handler: controllers/user.register
    events:
      - http:
          path: user
          method: post
          cors: true
  user-fetch:
    handler: controllers/user.fetch
    events:
      - http:
          path: user/{user_id}
          method: get
          cors: true
  user-wallet-create:
    handler: controllers/wallet.create
    events:
      - http:
          path: user/{user_id}/wallet
          method: post
          cors: true
  user-wallet-fetch:
    handler: controllers/wallet.create
    events:
      - http:
          path: user/{user_id}/wallet
          method: get
          cors: true

package:
  excludeDevDependencies: false